# Generated by Django 3.2.6 on 2021-08-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stripe_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='stripe_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
